### ISSUE TITLE
Objective-C has the same file extension of .m

### ISSUE THREAD

**Issue by yeison** [thedavidprice/language-matlab-octave#1]
In this example:  theta = pinv(X'_X)_X'*y;

The parser believes that this is indicating a string literal.  In fact, the single quote also shares the dual functionality of being the transpose symbol in matlab/octave.

**Comment by markogresak** [comment]
> I'll just have to remove the Objective-C package.

That's not a solution applicable to everyone.

Probably a better solution would be to press <kbd>Shift</kbd> + <kbd>Ctrl</kbd> + <kbd>L</kbd> and type `Octave` / `MATLAB`.
