### ISSUE TITLE
Comment blocks not fully supported

### ISSUE THREAD

**Issue by Clemasteredge** [thedavidprice/language-matlab-octave#14]
Matlab support comment blocks using %{ ... %}.
The comment block is disabled if the %{ is immediately followed by a character:

%{
... commented block ...
%}

%{/
... active block ...
%}

This feature does not work in the current Atom package. Both blocks are disabled/commented out.

**Comment by rlivings39** [comment]
This is one of the many issues in the TextMate grammar. MathWorks has published a grammar:

https://github.com/mathworks/MATLAB-Language-grammar

that is being used by GitHub's Linguist [PR1](https://github.com/github/linguist/issues/3904) [PR2](https://github.com/github/linguist/pull/4000) and the VSCode MATLAB extension ([PR1](https://github.com/Gimly/vscode-matlab/pull/74) & [PR2](https://github.com/Gimly/vscode-matlab/pull/80)

@thedavidprice would you be open to switching to use that grammar? I did some local experiments and it seems to address several issues including this one and more reported in https://github.com/JamesRitchie/language-matlab. If so, I'll send a PR.

**Comment by thedavidprice** [comment]
@rlivings39 Just spent some time going through this and the references. Quick reaction, I like this.

Yes to the “PR”. But I’m opening up a new issue for discussion and will link from here. If you do open the PR, please link it to the issue for discussion. 

Laslty, I’m heads down on a project for the next 2-3 weeks. I’ll watch this an help move it forward, but I won’t have much capacity to implement if anything comes up. Welcome and will need help on that end. 

Thanks!

**Comment by thedavidprice** [comment]
Ok, moved Mathworks grammar conversation to Issue #15

**Comment by thedavidprice** [comment]
Fixed with #16
