### ISSUE TITLE
Migrating from Textmate to Mathworks grammar

### ISSUE THREAD

**Issue by thedavidprice** [thedavidprice/language-matlab-octave#15]
_Picking up the conversation from [here](https://github.com/thedavidprice/language-matlab-octave/issues/14#issuecomment-513145089)._

This [comment](https://github.com/github/linguist/issues/3904#issuecomment-347582820) from /github/linguist/ provide helpful background.

Conversion from the Textmate bundle has always had issues. But we should keep continuity (look/feel) and demonstrate this is an improvement to current. If it is more of a wholesale change (per feedback), we might consider creating a new Atom package altogether. (In which case we can redirect people via README, etc.)

Lastly, this repo is fairly “quiet”. Meaning I have to assume 99% of installs are working good enough. So I’d like to enlarge the conversation if we move forward to include people who have forked or starred. See “for discussion" item below.

**For Discussion**
- [ ] Process going forward for managing Mathworks package as a dependency: who, how, document it, etc.
    - [ ] Additionally, how should we "version-lock" this package and Mathworks package? Both to clarify _which_ "version" of Mathworks was used to update this package release and to trigger a notice that there's a new "version" of Mathworks that requires updating and new release of this package.
- [x] How to enlarge this conversation including others using the package: stars, forks, … ?
- [x] Saw this [comment](https://github.com/github/linguist/issues/3904#issuecomment-359102001) about license. Make sure we do quick confirm that all’s fine.
- [x] Do we need to also need to address this fix per the VSCode PR [here](https://github.com/Gimly/vscode-matlab/pull/80)?
- [ ] Good ol’ Octave… anything to address regarding current grammar leaving as is?
- [ ] Lastly, I’m not sure how to think of this update in regards to semver and “breaking changes”. Meaning, I can foresee this potentially causing problem for users who’ve customized styling and for downstream forks. But I might be overthinking things. Regarless, will need a simple plan to communicate this update and handle Atoms auto-update notice (e.g. maybe we do something akin to RC labeling in attempt to get feedback, and then do final release bump to major v1…) Thoughts welcome here.

**Comment by rlivings39** [comment]
Some info I can add:

The license was updated to be BSD 2

https://github.com/mathworks/MATLAB-Language-grammar/blob/master/license.txt

In the version I'm testing with I converted the MathWorks grammar and then augmented that with the function highlighting to address the VSCode issue referenced. I'll submit a PR to show an example of what I had in mind. Hopefully that will make things more concrete.

**Comment by rlivings39** [comment]
I added https://github.com/thedavidprice/language-matlab-octave/pull/16#issuecomment-514568969 showing the differences on a much larger example to give more insight into the question of whether or not this is a wholesale change or incremental change. Most of the changes shown there I'd regard as bug fixes. I'm interested to hear others' thoughts.

**Comment by thedavidprice** [comment]
Opened #17 to address license requirements.

**Comment by thedavidprice** [comment]
@brian-lau @shur-greg @s-m-e @alpsayin @elpollodiablo84 @scrupeus @anthony-wang @luqmaan @gradyzhuo @fusion809 @jorgeborges @memming 

Please read this Issue thread regarding a major change in the Matlab grammar -- switching source from Textmate to MathWorks. Related PR #16 with examples of changes.

Before implementing this change, we would appreciate feedback and suggestions from others like yourself using the package currently.

Note: no changes will be made to Octave grammar.

**Comment by thedavidprice** [comment]
Note: I added a to-do regarding question about "version-locking" this package and Mathworks source package. Mathworks isn't using "release" process... how will we know 1) what Mathworks version we used to update our current release and 2) when we need to update because Mathworks has a new "version" release.

Am I making sense? Also, trying not to overthink it but definitely want to avoid future confusion.

**Comment by elpollodiablo84** [comment]
I'm one of the people who forked this package, mainly to correct some of the errors in question and implement the management of persistent variables.
I think that all the issues solved by this migration justify it, and personally I don'think the average user will be "upset" by the change. At most it will be strange to see plain looking variables instead of red ones! 😄 
My [package](https://atom.io/packages/language-matlab-plus) already solves all the issues related to PR [#16](https://github.com/thedavidprice/language-matlab-octave/pull/16), and I would like to continue maintaining it mainly for the persistent variables highlighting, so these changes will not impact me.
That being said, I will **gladly** help you in any way possible and I will follow closely the development of this migration!

**Comment by fusion809** [comment]
I don't really use Atom nowadays, aside from as a Julia IDE (i.e. with Juno), so I'm going to unsubscribe from this.

**Comment by rlivings39** [comment]
> Note: I added a to-do regarding question about "version-locking" this package and Mathworks source package. Mathworks isn't using "release" process... how will we know 1) what Mathworks version we used to update our current release and 2) when we need to update because Mathworks has a new "version" release.
> 
> Am I making sense? Also, trying not to overthink it but definitely want to avoid future confusion.

Good point. Adding @gauravsavadi who owns the MathWorks repo to get his thoughts on version tracking, releases, etc.

**Comment by thedavidprice** [comment]
@elpollodiablo84 Thank you for your comments and offer to help. Once we get through this change, would also welcome any suggestions for migration of improvements you’ve made. Otherwise @rlivings39 has done the work on #16 to the point where it’s ready to merge. Going to give it a little time for any further review from others including yourself.

**Comment by alpsayin** [comment]
Hi @thedavidprice, thanks for involving me in the conversation. But like fusion809 (intentionally not tagging) it's been a while for me since I used atom and I only made tiny mods to make it work for myself and definitely not an authority on this. So I'll have to take the bench on this one. I wish you guys good luck and thank for the good work that rest of us benefit :)

**Comment by rlivings39** [comment]
@thedavidprice, anything else I can provide right now to help keep this moving along?

**Comment by thedavidprice** [comment]
@rlivings39 Thanks for the prompt. Was traveling and lost mometum here.

I’ll work to turn around final tasks on my end and publish an RC1 in the next day or two. Only thing I don’t have a handle on is how to “lock” this package version to state/version of Mathworks. Or how to identify when Mathworks updates occur that should trigger an update on this end. Any suggestions @gauravsavadi ?

For now I could probably just add link to Mathworks commit hash in the README as a record… y/n?

**Comment by rlivings39** [comment]
Thanks @thedavidprice. Logging the commit hash in the README seems like a reasonable option short term. Other repos that have used this grammar have added it as a submodule which implicitly records the linked commit. Long term what you find ideal? Releases? Something else?

**Comment by thedavidprice** [comment]
@rlivings39 README = roger that. I’m working on this now: merging PRs, manually running through process for check, updating README as needed. Also pulled PRs to add MIT license and ditch init travis.yml setup.

For maintaining long-term, the only circumstance I don’t have an answer for is “how will I know when an update occurred on mathworks/MATLAB-Language-grammar that should trigger an update here?” If it’s as simple as you or @gauravsavadi opening an Issue or PR, that’s fine by me. I’ve subscribed to notifcations for that repo now — might be easier if there were releases, but could be fine as is. So I officially hand off this decision to you. Just keep me posted what you decide as I’m good either way 💯

**Comment by rlivings39** [comment]
I'm fine with opening issues/PRs for now until we come up with a more formal solution.

**Comment by thedavidprice** [comment]
@rlivings39 Take a look at the latest master branch. I’ve updated the README and also re-added your original `functions.cson` file. When I went through the process manually, I better understood your original intent and thought it would indeed be more clear for future updates. 

Please make sure I’ve documented correctly — and just let me know or PR otherwise. Once you give it a 👍 , I’ll do an RC release. Huge thanks!

**Comment by rlivings39** [comment]
Ship it!

Looks great to me @thedavidprice. Many thanks for all the help getting this ready to release.

**Comment by thedavidprice** [comment]
Protip: don't get fancy with apm publishing semver. So much grrrr.

That said, v1.0.1 is now in the world:  
https://github.com/thedavidprice/language-matlab-octave/releases/tag/v1.0.1

Thanks again for making this happen @rlivings39 I'll look for future PRs from the Mathworks repo. 🚀
