### ISSUE TITLE
Keywords not working properly 

### ISSUE THREAD

**Issue by r0oland** [thedavidprice/language-matlab-octave#4]
I am using a lot of Matlab toolboxes which have many extra keywords defined which should also be highlighted. For example, when defining a Class in Matlab, the "properties" keyword should be highlighted, but it is not. Other examples are "connect", "delete" and many more.
Now looking into the "m.cson" file i can see that most of these keywords are indeed defined, they just seem to be ignored. Do I have to configure which toolboxes I am using somewhere? Or am I missing something? 

Regards,
Joe

**Comment by thedavidprice** [comment]
Hi Joe. Haven't had a chance to look at this. Any progress since you last checked in?

- David

**Comment by r0oland** [comment]
Seems like the Syntax I was using didn't support enough colors...using the Default Sublime Syntax highliting solver the issue...

**Comment by thedavidprice** [comment]
Got it. Thanks for letting me know.
