### ISSUE TITLE
v0.1.2 while tagged is not in the Atom package registry

### ISSUE THREAD

**Issue by fusion809** [thedavidprice/language-matlab-octave#7]
Hi,

I've noticed that v0.1.2 is not in the Atom package registry (e.g., `apm install language-matlab-octave` will install v0.1.1 of this package as it is the latest version in the Atom package registry). Is this deliberate? If not please tag new releases with `apm publish` as this will register your new release with the Atom package registry. 

Thanks for your time,
Brenton

**Comment by thedavidprice** [comment]
Nope, not intentional. Good catch.

Should be fixed. Thanks.
