### ISSUE TITLE
Syntax highlighting in Markdown

### ISSUE THREAD

**Issue by ajeetdsouza** [thedavidprice/language-matlab-octave#8]
I'm using `language-matlab-octave` in a Markdown file, but syntax highlighting doesn't seem to work in code blocks:
```matlab
disp("Hello world")
```
I'm using `language-gfm` to display Markdown, and syntax highlighting works with other user-installed languages such as `language-haskell`.

It works great otherwise, however.

**Comment by thedavidprice** [comment]
This is likely a bit beyond me as all I’ve done is convert from the textmate bundle to generate the syntax highlighting. Initial guess is that there’s another step/config involved for your use case. I won’t be able to look into it, but I welcome any thoughts/dialogue or PR for testing.

I did notice my original conversion was about 2 years+ out of sync with the original textmate bundle, which is better maintained than mine. I just performed a version update from the bundle and released `v0.2.0` of this package. From the outset, seems that only minor updates have occurred. But please do update your local version of this package and take it for a spin. Definitely let me know if there are any issues. And would be great to hear back about noticeable improvements.

**Comment by ajeetdsouza** [comment]
Hi, thanks a lot! I tested the new version, and it seems to work fine. However, syntax highlighting for double quotes doesn't seem to work very well. On my PC, they are highlighted with an ugly red colour. Any ideas?

**Comment by thedavidprice** [comment]
You have a couple options here. The more overkill/ambitious (but fun if you want to learn how to publish a package) would be to fork/clone this repo, make the edits you’d like, then publish and install your own Atom Package. More on atom packages here:
https://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/

Atom allows you to override syntax themes yourself, which is likely what you’d want to try in this case. Here are a couple google search results to get you started:
https://discuss.atom.io/t/changing-syntax-highlighting-colours/12534
https://discuss.atom.io/t/overriding-syntax-theme/21603
https://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/ (note: you don’t need to create a theme, just thought it might be helpful overview)
